version: '3'
services:
  app:
    build: .
    container_name: go-video-encoder
    volumes:
      - .:/go/src/
  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=encoder
    ports:
      - "5432:5432"